/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestAuthRouteImport } from './routes/test-auth'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SignoutRouteImport } from './routes/signout'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvitationInviteIDRouteImport } from './routes/invitation.$inviteID'
import { Route as AuthedDashboardRouteRouteImport } from './routes/_authed.dashboard.route'
import { Route as AuthedDashboardIndexRouteImport } from './routes/_authed.dashboard.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AuthedDashboardInvitesNewRouteImport } from './routes/_authed.dashboard.invites.new'
import { Route as AuthedDashboardInvitesInviteIDRouteImport } from './routes/_authed.dashboard.invites.$inviteID'
import { Route as AuthedDashboardInvitesInviteIDIndexRouteImport } from './routes/_authed.dashboard.invites.$inviteID.index'
import { Route as AuthedDashboardInvitesInviteIDEditRouteImport } from './routes/_authed.dashboard.invites.$inviteID.edit'

const TestAuthRoute = TestAuthRouteImport.update({
  id: '/test-auth',
  path: '/test-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SignoutRoute = SignoutRouteImport.update({
  id: '/signout',
  path: '/signout',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationInviteIDRoute = InvitationInviteIDRouteImport.update({
  id: '/invitation/$inviteID',
  path: '/invitation/$inviteID',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRouteRoute = AuthedDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardIndexRoute = AuthedDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedDashboardRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardInvitesNewRoute =
  AuthedDashboardInvitesNewRouteImport.update({
    id: '/invites/new',
    path: '/invites/new',
    getParentRoute: () => AuthedDashboardRouteRoute,
  } as any)
const AuthedDashboardInvitesInviteIDRoute =
  AuthedDashboardInvitesInviteIDRouteImport.update({
    id: '/invites/$inviteID',
    path: '/invites/$inviteID',
    getParentRoute: () => AuthedDashboardRouteRoute,
  } as any)
const AuthedDashboardInvitesInviteIDIndexRoute =
  AuthedDashboardInvitesInviteIDIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedDashboardInvitesInviteIDRoute,
  } as any)
const AuthedDashboardInvitesInviteIDEditRoute =
  AuthedDashboardInvitesInviteIDEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthedDashboardInvitesInviteIDRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signout': typeof SignoutRoute
  '/signup': typeof SignupRoute
  '/test-auth': typeof TestAuthRoute
  '/dashboard': typeof AuthedDashboardRouteRouteWithChildren
  '/invitation/$inviteID': typeof InvitationInviteIDRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/': typeof AuthedDashboardIndexRoute
  '/dashboard/invites/$inviteID': typeof AuthedDashboardInvitesInviteIDRouteWithChildren
  '/dashboard/invites/new': typeof AuthedDashboardInvitesNewRoute
  '/dashboard/invites/$inviteID/edit': typeof AuthedDashboardInvitesInviteIDEditRoute
  '/dashboard/invites/$inviteID/': typeof AuthedDashboardInvitesInviteIDIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signout': typeof SignoutRoute
  '/signup': typeof SignupRoute
  '/test-auth': typeof TestAuthRoute
  '/invitation/$inviteID': typeof InvitationInviteIDRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
  '/dashboard/invites/new': typeof AuthedDashboardInvitesNewRoute
  '/dashboard/invites/$inviteID/edit': typeof AuthedDashboardInvitesInviteIDEditRoute
  '/dashboard/invites/$inviteID': typeof AuthedDashboardInvitesInviteIDIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/signin': typeof SigninRoute
  '/signout': typeof SignoutRoute
  '/signup': typeof SignupRoute
  '/test-auth': typeof TestAuthRoute
  '/_authed/dashboard': typeof AuthedDashboardRouteRouteWithChildren
  '/invitation/$inviteID': typeof InvitationInviteIDRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/dashboard/': typeof AuthedDashboardIndexRoute
  '/_authed/dashboard/invites/$inviteID': typeof AuthedDashboardInvitesInviteIDRouteWithChildren
  '/_authed/dashboard/invites/new': typeof AuthedDashboardInvitesNewRoute
  '/_authed/dashboard/invites/$inviteID/edit': typeof AuthedDashboardInvitesInviteIDEditRoute
  '/_authed/dashboard/invites/$inviteID/': typeof AuthedDashboardInvitesInviteIDIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/signout'
    | '/signup'
    | '/test-auth'
    | '/dashboard'
    | '/invitation/$inviteID'
    | '/api/auth/$'
    | '/dashboard/'
    | '/dashboard/invites/$inviteID'
    | '/dashboard/invites/new'
    | '/dashboard/invites/$inviteID/edit'
    | '/dashboard/invites/$inviteID/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signout'
    | '/signup'
    | '/test-auth'
    | '/invitation/$inviteID'
    | '/api/auth/$'
    | '/dashboard'
    | '/dashboard/invites/new'
    | '/dashboard/invites/$inviteID/edit'
    | '/dashboard/invites/$inviteID'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/signin'
    | '/signout'
    | '/signup'
    | '/test-auth'
    | '/_authed/dashboard'
    | '/invitation/$inviteID'
    | '/api/auth/$'
    | '/_authed/dashboard/'
    | '/_authed/dashboard/invites/$inviteID'
    | '/_authed/dashboard/invites/new'
    | '/_authed/dashboard/invites/$inviteID/edit'
    | '/_authed/dashboard/invites/$inviteID/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  SigninRoute: typeof SigninRoute
  SignoutRoute: typeof SignoutRoute
  SignupRoute: typeof SignupRoute
  TestAuthRoute: typeof TestAuthRoute
  InvitationInviteIDRoute: typeof InvitationInviteIDRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-auth': {
      id: '/test-auth'
      path: '/test-auth'
      fullPath: '/test-auth'
      preLoaderRoute: typeof TestAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signout': {
      id: '/signout'
      path: '/signout'
      fullPath: '/signout'
      preLoaderRoute: typeof SignoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitation/$inviteID': {
      id: '/invitation/$inviteID'
      path: '/invitation/$inviteID'
      fullPath: '/invitation/$inviteID'
      preLoaderRoute: typeof InvitationInviteIDRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/': {
      id: '/_authed/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthedDashboardIndexRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard/invites/new': {
      id: '/_authed/dashboard/invites/new'
      path: '/invites/new'
      fullPath: '/dashboard/invites/new'
      preLoaderRoute: typeof AuthedDashboardInvitesNewRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/_authed/dashboard/invites/$inviteID': {
      id: '/_authed/dashboard/invites/$inviteID'
      path: '/invites/$inviteID'
      fullPath: '/dashboard/invites/$inviteID'
      preLoaderRoute: typeof AuthedDashboardInvitesInviteIDRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/_authed/dashboard/invites/$inviteID/': {
      id: '/_authed/dashboard/invites/$inviteID/'
      path: '/'
      fullPath: '/dashboard/invites/$inviteID/'
      preLoaderRoute: typeof AuthedDashboardInvitesInviteIDIndexRouteImport
      parentRoute: typeof AuthedDashboardInvitesInviteIDRoute
    }
    '/_authed/dashboard/invites/$inviteID/edit': {
      id: '/_authed/dashboard/invites/$inviteID/edit'
      path: '/edit'
      fullPath: '/dashboard/invites/$inviteID/edit'
      preLoaderRoute: typeof AuthedDashboardInvitesInviteIDEditRouteImport
      parentRoute: typeof AuthedDashboardInvitesInviteIDRoute
    }
  }
}

interface AuthedDashboardInvitesInviteIDRouteChildren {
  AuthedDashboardInvitesInviteIDEditRoute: typeof AuthedDashboardInvitesInviteIDEditRoute
  AuthedDashboardInvitesInviteIDIndexRoute: typeof AuthedDashboardInvitesInviteIDIndexRoute
}

const AuthedDashboardInvitesInviteIDRouteChildren: AuthedDashboardInvitesInviteIDRouteChildren =
  {
    AuthedDashboardInvitesInviteIDEditRoute:
      AuthedDashboardInvitesInviteIDEditRoute,
    AuthedDashboardInvitesInviteIDIndexRoute:
      AuthedDashboardInvitesInviteIDIndexRoute,
  }

const AuthedDashboardInvitesInviteIDRouteWithChildren =
  AuthedDashboardInvitesInviteIDRoute._addFileChildren(
    AuthedDashboardInvitesInviteIDRouteChildren,
  )

interface AuthedDashboardRouteRouteChildren {
  AuthedDashboardIndexRoute: typeof AuthedDashboardIndexRoute
  AuthedDashboardInvitesInviteIDRoute: typeof AuthedDashboardInvitesInviteIDRouteWithChildren
  AuthedDashboardInvitesNewRoute: typeof AuthedDashboardInvitesNewRoute
}

const AuthedDashboardRouteRouteChildren: AuthedDashboardRouteRouteChildren = {
  AuthedDashboardIndexRoute: AuthedDashboardIndexRoute,
  AuthedDashboardInvitesInviteIDRoute:
    AuthedDashboardInvitesInviteIDRouteWithChildren,
  AuthedDashboardInvitesNewRoute: AuthedDashboardInvitesNewRoute,
}

const AuthedDashboardRouteRouteWithChildren =
  AuthedDashboardRouteRoute._addFileChildren(AuthedDashboardRouteRouteChildren)

interface AuthedRouteChildren {
  AuthedDashboardRouteRoute: typeof AuthedDashboardRouteRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRouteRoute: AuthedDashboardRouteRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  SigninRoute: SigninRoute,
  SignoutRoute: SignoutRoute,
  SignupRoute: SignupRoute,
  TestAuthRoute: TestAuthRoute,
  InvitationInviteIDRoute: InvitationInviteIDRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
